services:

  postgres:
    image: postgres:18.6
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: postgres
    ports:
      - "127.0.0.1:${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready -h localhost -U "$$POSTGRES_USER" -d "$$POSTGRES_DB"
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  rabbitmq:
    image: rabbitmq:4.3.6-management
    hostname: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    ports:
      - "127.0.0.1:${RABBITMQ_PORT}:5672"
      - "127.0.0.1:${RABBITMQ_MANAGEMENT_PORT}:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test:
        - CMD-SHELL
        - rabbitmq-diagnostics -q check_running && rabbitmq-diagnostics -q check_port_connectivity
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  clientes:
    image: clientes-api:local
    pull_policy: never # solo permite imagenes locales
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ConnectionStrings__Database: "Host=postgres;Port=5432;Database=${CLIENTES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}"
      ConnectionStrings__RabbitMQ: "amqp://${RABBITMQ_USER}:${RABBITMQ_PASSWORD}@rabbitmq:5672/"
    ports:
      - "127.0.0.1:${CLIENTES_PORT}:8080"
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  cuentas:
    image: cuentas-api:local
    pull_policy: never # solo permite imagenes locales
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ConnectionStrings__Database: "Host=postgres;Port=5432;Database=${CUENTAS_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}"
      ConnectionStrings__RabbitMQ: "amqp://${RABBITMQ_USER}:${RABBITMQ_PASSWORD}@rabbitmq:5672/"
    ports:
      - "127.0.0.1:${CUENTAS_PORT}:8080"
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

volumes:
  postgres_data:
  rabbitmq_data: