<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\Clientes.Application\Clientes.Application.csproj" />
    <ProjectReference Include="..\Clientes.Infrastructure\Clientes.Infrastructure.csproj" />
    <ProjectReference Include="..\..\Shared\Shared.Api\Shared.Api.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

</Project>
