<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\Cuentas.Application\Cuentas.Application.csproj" />
    <ProjectReference Include="..\Cuentas.Infrastructure\Cuentas.Infrastructure.csproj" />
    <ProjectReference Include="..\..\Shared\Shared.Api\Shared.Api.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>2348d6ee-4f00-4876-b534-3319c3d1c6a1</UserSecretsId>
  </PropertyGroup>

</Project>
